### ISSUE TITLE
Registering a new account should land you on the profile page

### ISSUE THREAD

**Issue by axv3658** [JDonut/UsabilityProject#22]
Currently you are redirected to the home page

**Comment by JDonut** [comment]
That is how I originally had it. When you create a new profile though, you dont have any followed charities, posts, or donated amounts, so its essentially just an empty page. The only operation you can do is clicking the icon to bring you to the featured charities list, so I just had account creation redirect there.

**Comment by mdw7326** [comment]
As per the fact that a new user won't have any followed charities, we might want to fake some initial data per #20
