### ISSUE TITLE
Order of comments should have most recent at top

### ISSUE THREAD

**Issue by mdw7326** [JDonut/UsabilityProject#27]

**Comment by ermammoser** [comment]
Thinking about it, to make it emulate facebook comments, we could keep the current order but move the "load older comments" button to the top of the panel and the comment box to the bottom.  This would be easier for reading

**Comment by mdw7326** [comment]
sounds good

**Comment by mdw7326** [comment]
Actually, this would be odd I think because of the way our entire layout is set up. If we have the "load more comments" button on the top and the form a the bottom, our form is going to arbitrarily be pushed further down the screen, which isn't good. I'm leaning more towards the original idea now (just switching the comment order and leaving the button/form in the same spot)

**Comment by mdw7326** [comment]
@JDonut It looks like the "order" field in the comments json stuffs is never actually used. what's a quick way to sort by order in the js file?

**Comment by mdw7326** [comment]
Nevermind, got it: 

```
    $scope.postComment = function() {
        if($scope.commentPostContent.content) {
            $scope.userPosts.push({
                order : $scope.UserPostOrder,
                userName : userService.email,
                userImg : userService.img,
                content : $scope.commentPostContent.content
            });
            $scope.commentPostContent.content = null;
        }
        $scope.UserPostOrder--;
        $scope.userPosts.sort(function(a,b){
          return a.order - b.order
        })
    }
```
