### ISSUE TITLE
Search bar moves on first interaction

### ISSUE THREAD

**Issue by mdw7326** [JDonut/UsabilityProject#8]
If you do a complete refresh of our index page, the search bar is off-center, slightly to the right of where it should be. When you click it, it shifts to the left. I'm not sure why, I don't see any styles changing or anything like that.

**Comment by mdw7326** [comment]
Did the fix for this ever get merged in @JDonut ?

**Comment by JDonut** [comment]
I never looked into this. Did you have a fix for it?

**Comment by mdw7326** [comment]
Will be fixed if #31 is merged in
