### ISSUE TITLE
Post Comment

### ISSUE THREAD

**Issue by mdw7326** [JDonut/UsabilityProject#9]
We should add a way of interacting with the "Post" button for comments on charity pages. We can full out add the comment to the JSON or just fake it somehow while the user is on the page. Whichever is easiest really

**Comment by JDonut** [comment]
Done here:
https://github.com/JDonut/UsabilityProject/commit/28acc5d364dfeac071f7e08185b1592754176653

**Comment by JDonut** [comment]
Ignore my fumbling, I'm just looking for a nice way to close this that doesn't just look like I ignored it.
